### ISSUE TITLE
Laravel 8 Support

### ISSUE THREAD

**Issue by Secusaurus** [signifly/laravel-janitor#13]
Hi there,

thanks for your awesome package!

I was just trying to upgrade my project to Laravel 8. I get an error that the `guzzle`-dependency doesn't work at the same time as the requirement for Laravel 8 (which is `^7.0.1`).
On the other hand I saw that you commited some changes focusing on Laravel 8 support already a month ago. Perhaps it's just a matter of setting up a release for composer?

Thanks in advance!
Chris

**Comment by pactode** [comment]
Hi!

Thanks for using our package. I have just made a new release with L8 support.

Take care,
Morten
