### ISSUE TITLE
Laravel 9 support

### ISSUE THREAD

**Issue by Innercode** [signifly/laravel-janitor#15]
Hi,

First of all, thanks for this package.
Can you update the composer.json file in order to support Laravel 9?

Thanks in advance!

**Comment by Innercode** [comment]
Is this package still maintained?

**Comment by emilhorlyck** [comment]
We are in a transition, but let's see if we can get back to maintaining this as well.

**Comment by Razorsheep** [comment]
Updated to v9 and v10.
