### ISSUE TITLE
Other Clients?

### ISSUE THREAD

**Issue by lloy0076** [signifly/laravel-janitor#2]
https://github.com/signifly/laravel-janitor/blob/27691098b4fe4d5befd59429b60e4efe4ed958f4/src/PassportProxy.php#L114

This fetches the first client, however it is possible for there to be more than one client.

Is there any plan to support:

- Setting a default client by configuration?
- Selecting a client somehow?

**Comment by pactode** [comment]
@lloy0076 Yes, that's definitely in the pipeline. Feel free to make a pull request if you have an idea of how it should be implemented. My initial thought is to add a ClientCredentialsProvider, which is swappable in the configuration.
