### ISSUE TITLE
Allow for Different User Providers

### ISSUE THREAD

**Issue by lloy0076** [signifly/laravel-janitor#4]
https://github.com/signifly/laravel-janitor/blob/27691098b4fe4d5befd59429b60e4efe4ed958f4/src/AbstractProxy.php#L43

It's hard coded as:

        $userClass = config('auth.providers.users.model');

However that's an assumption.

I wonder if there should be some level of configuration here? That'd be a good default but it may not _always_ hold true.

**Comment by pactode** [comment]
Fixed in bacb747.
