### ISSUE TITLE
Use the User Provider Contract Maybe?

### ISSUE THREAD

**Issue by lloy0076** [signifly/laravel-janitor#5]
https://github.com/signifly/laravel-janitor/blob/27691098b4fe4d5befd59429b60e4efe4ed958f4/src/PassportProxy.php#L29

This seems to go searching the user provider itself (and it assumes it's some sort of Eloquent/DB-ish thing too). It should, though, assume that the provider implements the User Provider Contract (lluminate\Contracts\Auth\UserProvider):

* https://laravel.com/docs/5.8/authentication#the-user-provider-contract

...and just call it rather than do all the work itself.

**Comment by pactode** [comment]
Great idea. I'll update the code accordingly.

Thanks
