### ISSUE TITLE
Client ID field as a UUID

### ISSUE THREAD

**Issue by seriousjelly** [signifly/laravel-janitor#9]
Great package! Thanks for this, it has helped me out. 

A couple of issues/questions:

1) It would be great if we had the ability to override the Passport model used. In my app I have extended the Passport model to allow for the ID column to be UUID's. At the moment, my application fails as the Client ID that is returned from getClientCredentials() function is 2 when in actual fact it is 02f5b33a-5735-4fe6-87bf-2e062d745271.

2) Allow for the ability to define a client, as it stands it just grabs the first password client.

**Comment by seriousjelly** [comment]
Oh, sorry, in fact I can see that some else has already raised point 2.

**Comment by seriousjelly** [comment]
I have created a pull request for this. It seems to resolve my issue. 

This is one of my first ever pull requests so apologies if something isn't quite right :/ 

#10

**Comment by pactode** [comment]
Fixed in #10
